name: exchange
description: "A currency exchange calculator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  drift: ^2.28.1
  drift_flutter: ^0.2.6
  path_provider: ^2.1.5
  equatable: ^2.0.7
  copy_with_extension: ^6.0.1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  dio: ^5.9.0
  retrofit: ^4.7.2
  flutter_riverpod: ^2.6.1
  collection: ^1.19.1
  theme_tailor_annotation: ^3.1.0
  google_fonts: ^6.3.1
  auto_route: ^10.1.2
  flutter_animate: ^4.5.2
  animated_switcher_plus: ^1.4.0
  connectivity_plus: ^6.1.5
  intl: ^0.20.2
  fl_chart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5
  drift_dev: ^2.28.0
  copy_with_extension_gen: ^6.0.1
  slang_build_runner: ^4.8.1
  retrofit_generator: ^9.7.0
  theme_tailor: ^3.0.3
  auto_route_generator: ^10.1.0

flutter:
  uses-material-design: true